import { defineSchema } from "convex/server";
import {
  usersTable,
  orgsTable,
  membershipsTable,
  servicesTable,
  orgServicesTable,
  profilesTable,
  requestsTable,
  eventsTable,
  documentsTable,
  postsTable,
  conversationsTable,
  formTemplatesTable,
  appointmentsTable,
  agentSchedulesTable,
  messagesTable,
  documentTemplatesTable,
  paymentsTable,
  documentVerificationsTable,
  agentNotesTable,
  consularRegistrationsTable,
  consularNotificationsTable,
  cvTable,
  childProfilesTable,
  auditLogTable,
  notificationsTable,
  tutorialsTable,
  communityEventsTable,
  digitalMailTable,
  deliveryPackagesTable,
  associationsTable,
  associationMembersTable,
  associationClaimsTable,
  companiesTable,
  companyMembersTable,
  positionsTable,
  ministryGroupsTable,
  securityPoliciesTable,
  maintenanceConfigTable,
  ticketsTable,
  meetingsTable,
  callLinesTable,
  countersTable,
  signauxTable,
  historiqueActionsTable,
  configSystemeTable,
  metriquesTable,
  poidsAdaptatifsTable,
  gcpMetricsCacheTable,
  cardDesignsTable,
} from "./schemas";

export default defineSchema({
  users: usersTable,
  orgs: orgsTable,
  memberships: membershipsTable,
  services: servicesTable,
  orgServices: orgServicesTable,
  profiles: profilesTable,
  requests: requestsTable,
  events: eventsTable,
  documents: documentsTable,
  posts: postsTable,
  conversations: conversationsTable,
  formTemplates: formTemplatesTable,
  appointments: appointmentsTable,
  agentSchedules: agentSchedulesTable,
  messages: messagesTable,
  documentTemplates: documentTemplatesTable,
  payments: paymentsTable,
  documentVerifications: documentVerificationsTable,
  agentNotes: agentNotesTable,
  consularRegistrations: consularRegistrationsTable,
  consularNotifications: consularNotificationsTable,
  cv: cvTable,
  childProfiles: childProfilesTable,
  auditLog: auditLogTable,
  notifications: notificationsTable,
  tutorials: tutorialsTable,
  communityEvents: communityEventsTable,
  digitalMail: digitalMailTable,
  deliveryPackages: deliveryPackagesTable,
  associations: associationsTable,
  associationMembers: associationMembersTable,
  associationClaims: associationClaimsTable,
  companies: companiesTable,
  companyMembers: companyMembersTable,
  positions: positionsTable,
  ministryGroups: ministryGroupsTable,
  securityPolicies: securityPoliciesTable,
  maintenanceConfig: maintenanceConfigTable,
  tickets: ticketsTable,
  meetings: meetingsTable,
  callLines: callLinesTable,
  counters: countersTable,
  signaux: signauxTable,
  historiqueActions: historiqueActionsTable,
  configSysteme: configSystemeTable,
  metriques: metriquesTable,
  poidsAdaptatifs: poidsAdaptatifsTable,
  gcpMetricsCache: gcpMetricsCacheTable,
  cardDesigns: cardDesignsTable,
});
