/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStatisticsRouteImport } from './routes/_app/statistics'
import { Route as AppPrintQueueRouteImport } from './routes/_app/print-queue'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts/index'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings/index'
import { Route as AppDesignerIndexRouteImport } from './routes/_app/designer/index'
import { Route as AppConsularRegistryIndexRouteImport } from './routes/_app/consular-registry/index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app/appointments/index'
import { Route as AppRequestsReferenceRouteImport } from './routes/_app/requests/$reference'
import { Route as AppProfilesProfileIdRouteImport } from './routes/_app/profiles/$profileId'
import { Route as AppPostsNewRouteImport } from './routes/_app/posts/new'
import { Route as AppDesignerTemplateIdRouteImport } from './routes/_app/designer/$templateId'
import { Route as AppConsularRegistryPrintQueueRouteImport } from './routes/_app/consular-registry/print-queue'
import { Route as AppAppointmentsAppointmentIdRouteImport } from './routes/_app/appointments/$appointmentId'
import { Route as AppServicesServiceIdEditRouteImport } from './routes/_app/services/$serviceId.edit'
import { Route as AppPostsPostIdEditRouteImport } from './routes/_app/posts/$postId.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintQueueRoute = AppPrintQueueRouteImport.update({
  id: '/print-queue',
  path: '/print-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignerIndexRoute = AppDesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsularRegistryIndexRoute =
  AppConsularRegistryIndexRouteImport.update({
    id: '/consular-registry/',
    path: '/consular-registry/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsReferenceRoute = AppRequestsReferenceRouteImport.update({
  id: '/requests/$reference',
  path: '/requests/$reference',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesProfileIdRoute = AppProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignerTemplateIdRoute = AppDesignerTemplateIdRouteImport.update({
  id: '/designer/$templateId',
  path: '/designer/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppConsularRegistryPrintQueueRoute =
  AppConsularRegistryPrintQueueRouteImport.update({
    id: '/consular-registry/print-queue',
    path: '/consular-registry/print-queue',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppointmentsAppointmentIdRoute =
  AppAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceIdEditRoute =
  AppServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/calls': typeof AppCallsRoute
  '/payments': typeof AppPaymentsRoute
  '/print-queue': typeof AppPrintQueueRoute
  '/statistics': typeof AppStatisticsRoute
  '/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/designer/$templateId': typeof AppDesignerTemplateIdRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$reference': typeof AppRequestsReferenceRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/consular-registry/': typeof AppConsularRegistryIndexRoute
  '/designer/': typeof AppDesignerIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/posts/': typeof AppPostsIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/calls': typeof AppCallsRoute
  '/payments': typeof AppPaymentsRoute
  '/print-queue': typeof AppPrintQueueRoute
  '/statistics': typeof AppStatisticsRoute
  '/': typeof AppIndexRoute
  '/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/designer/$templateId': typeof AppDesignerTemplateIdRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$reference': typeof AppRequestsReferenceRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/consular-registry': typeof AppConsularRegistryIndexRoute
  '/designer': typeof AppDesignerIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/posts': typeof AppPostsIndexRoute
  '/requests': typeof AppRequestsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/print-queue': typeof AppPrintQueueRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/_app/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/_app/designer/$templateId': typeof AppDesignerTemplateIdRoute
  '/_app/posts/new': typeof AppPostsNewRoute
  '/_app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/_app/requests/$reference': typeof AppRequestsReferenceRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/consular-registry/': typeof AppConsularRegistryIndexRoute
  '/_app/designer/': typeof AppDesignerIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/posts/': typeof AppPostsIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/_app/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/calls'
    | '/payments'
    | '/print-queue'
    | '/statistics'
    | '/appointments/$appointmentId'
    | '/consular-registry/print-queue'
    | '/designer/$templateId'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$reference'
    | '/appointments/'
    | '/consular-registry/'
    | '/designer/'
    | '/meetings/'
    | '/posts/'
    | '/requests/'
    | '/services/'
    | '/settings/'
    | '/team/'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/calls'
    | '/payments'
    | '/print-queue'
    | '/statistics'
    | '/'
    | '/appointments/$appointmentId'
    | '/consular-registry/print-queue'
    | '/designer/$templateId'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$reference'
    | '/appointments'
    | '/consular-registry'
    | '/designer'
    | '/meetings'
    | '/posts'
    | '/requests'
    | '/services'
    | '/settings'
    | '/team'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/calls'
    | '/_app/payments'
    | '/_app/print-queue'
    | '/_app/statistics'
    | '/_app/'
    | '/_app/appointments/$appointmentId'
    | '/_app/consular-registry/print-queue'
    | '/_app/designer/$templateId'
    | '/_app/posts/new'
    | '/_app/profiles/$profileId'
    | '/_app/requests/$reference'
    | '/_app/appointments/'
    | '/_app/consular-registry/'
    | '/_app/designer/'
    | '/_app/meetings/'
    | '/_app/posts/'
    | '/_app/requests/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/team/'
    | '/_app/posts/$postId/edit'
    | '/_app/services/$serviceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print-queue': {
      id: '/_app/print-queue'
      path: '/print-queue'
      fullPath: '/print-queue'
      preLoaderRoute: typeof AppPrintQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designer/': {
      id: '/_app/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof AppDesignerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consular-registry/': {
      id: '/_app/consular-registry/'
      path: '/consular-registry'
      fullPath: '/consular-registry/'
      preLoaderRoute: typeof AppConsularRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/$reference': {
      id: '/_app/requests/$reference'
      path: '/requests/$reference'
      fullPath: '/requests/$reference'
      preLoaderRoute: typeof AppRequestsReferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$profileId': {
      id: '/_app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof AppProfilesProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/new': {
      id: '/_app/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designer/$templateId': {
      id: '/_app/designer/$templateId'
      path: '/designer/$templateId'
      fullPath: '/designer/$templateId'
      preLoaderRoute: typeof AppDesignerTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consular-registry/print-queue': {
      id: '/_app/consular-registry/print-queue'
      path: '/consular-registry/print-queue'
      fullPath: '/consular-registry/print-queue'
      preLoaderRoute: typeof AppConsularRegistryPrintQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/$appointmentId': {
      id: '/_app/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceId/edit': {
      id: '/_app/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AppServicesServiceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/$postId/edit': {
      id: '/_app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPrintQueueRoute: typeof AppPrintQueueRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentsAppointmentIdRoute: typeof AppAppointmentsAppointmentIdRoute
  AppConsularRegistryPrintQueueRoute: typeof AppConsularRegistryPrintQueueRoute
  AppDesignerTemplateIdRoute: typeof AppDesignerTemplateIdRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppProfilesProfileIdRoute: typeof AppProfilesProfileIdRoute
  AppRequestsReferenceRoute: typeof AppRequestsReferenceRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppConsularRegistryIndexRoute: typeof AppConsularRegistryIndexRoute
  AppDesignerIndexRoute: typeof AppDesignerIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
  AppServicesServiceIdEditRoute: typeof AppServicesServiceIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPrintQueueRoute: AppPrintQueueRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppointmentsAppointmentIdRoute: AppAppointmentsAppointmentIdRoute,
  AppConsularRegistryPrintQueueRoute: AppConsularRegistryPrintQueueRoute,
  AppDesignerTemplateIdRoute: AppDesignerTemplateIdRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppProfilesProfileIdRoute: AppProfilesProfileIdRoute,
  AppRequestsReferenceRoute: AppRequestsReferenceRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppConsularRegistryIndexRoute: AppConsularRegistryIndexRoute,
  AppDesignerIndexRoute: AppDesignerIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
  AppServicesServiceIdEditRoute: AppServicesServiceIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
