/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as AppAssociationsRouteImport } from './routes/_app/associations'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTutorialsIndexRouteImport } from './routes/_app/tutorials/index'
import { Route as AppSupportIndexRouteImport } from './routes/_app/support/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts/index'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppMonitoringIndexRouteImport } from './routes/_app/monitoring/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppAuditLogsIndexRouteImport } from './routes/_app/audit-logs/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppTutorialsNewRouteImport } from './routes/_app/tutorials/new'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app/support/$ticketId'
import { Route as AppServicesNewRouteImport } from './routes/_app/services/new'
import { Route as AppRequestsRequestIdRouteImport } from './routes/_app/requests/$requestId'
import { Route as AppProfilesProfileIdRouteImport } from './routes/_app/profiles/$profileId'
import { Route as AppPostsNewRouteImport } from './routes/_app/posts/new'
import { Route as AppOrgsNewRouteImport } from './routes/_app/orgs/new'
import { Route as AppOrgsOrgIdRouteImport } from './routes/_app/orgs/$orgId'
import { Route as AppEventsNewRouteImport } from './routes/_app/events/new'
import { Route as AppConfigServicesRouteImport } from './routes/_app/config/services'
import { Route as AppConfigRepresentationsRouteImport } from './routes/_app/config/representations'
import { Route as AppConfigPositionsRouteImport } from './routes/_app/config/positions'
import { Route as AppConfigModulesRouteImport } from './routes/_app/config/modules'
import { Route as AppTutorialsTutorialIdEditRouteImport } from './routes/_app/tutorials/$tutorialId.edit'
import { Route as AppServicesServiceIdFormBuilderRouteImport } from './routes/_app/services/$serviceId_.form-builder'
import { Route as AppServicesServiceIdEditRouteImport } from './routes/_app/services/$serviceId_.edit'
import { Route as AppPostsPostIdEditRouteImport } from './routes/_app/posts/$postId.edit'
import { Route as AppOrgsOrgIdEditRouteImport } from './routes/_app/orgs/$orgId_.edit'
import { Route as AppEventsEventIdEditRouteImport } from './routes/_app/events/$eventId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssociationsRoute = AppAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsIndexRoute = AppTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringIndexRoute = AppMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsIndexRoute = AppAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsNewRoute = AppTutorialsNewRouteImport.update({
  id: '/tutorials/new',
  path: '/tutorials/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesNewRoute = AppServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesProfileIdRoute = AppProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsNewRoute = AppOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsOrgIdRoute = AppOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServicesRoute = AppConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRepresentationsRoute =
  AppConfigRepresentationsRouteImport.update({
    id: '/config/representations',
    path: '/config/representations',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigPositionsRoute = AppConfigPositionsRouteImport.update({
  id: '/config/positions',
  path: '/config/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigModulesRoute = AppConfigModulesRouteImport.update({
  id: '/config/modules',
  path: '/config/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsTutorialIdEditRoute =
  AppTutorialsTutorialIdEditRouteImport.update({
    id: '/tutorials/$tutorialId/edit',
    path: '/tutorials/$tutorialId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceIdFormBuilderRoute =
  AppServicesServiceIdFormBuilderRouteImport.update({
    id: '/services/$serviceId_/form-builder',
    path: '/services/$serviceId/form-builder',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceIdEditRoute =
  AppServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId_/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsOrgIdEditRoute = AppOrgsOrgIdEditRouteImport.update({
  id: '/orgs/$orgId_/edit',
  path: '/orgs/$orgId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/associations': typeof AppAssociationsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/config/modules': typeof AppConfigModulesRoute
  '/config/positions': typeof AppConfigPositionsRoute
  '/config/representations': typeof AppConfigRepresentationsRoute
  '/config/services': typeof AppConfigServicesRoute
  '/events/new': typeof AppEventsNewRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/services/new': typeof AppServicesNewRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tutorials/new': typeof AppTutorialsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/audit-logs/': typeof AppAuditLogsIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/monitoring/': typeof AppMonitoringIndexRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/posts/': typeof AppPostsIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/tutorials/': typeof AppTutorialsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/services/$serviceId/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRoutesByTo {
  '/associations': typeof AppAssociationsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/': typeof AppIndexRoute
  '/config/modules': typeof AppConfigModulesRoute
  '/config/positions': typeof AppConfigPositionsRoute
  '/config/representations': typeof AppConfigRepresentationsRoute
  '/config/services': typeof AppConfigServicesRoute
  '/events/new': typeof AppEventsNewRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/services/new': typeof AppServicesNewRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tutorials/new': typeof AppTutorialsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/audit-logs': typeof AppAuditLogsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/monitoring': typeof AppMonitoringIndexRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/posts': typeof AppPostsIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/requests': typeof AppRequestsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/tutorials': typeof AppTutorialsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/services/$serviceId/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/associations': typeof AppAssociationsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/config/modules': typeof AppConfigModulesRoute
  '/_app/config/positions': typeof AppConfigPositionsRoute
  '/_app/config/representations': typeof AppConfigRepresentationsRoute
  '/_app/config/services': typeof AppConfigServicesRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/_app/orgs/new': typeof AppOrgsNewRoute
  '/_app/posts/new': typeof AppPostsNewRoute
  '/_app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/_app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/_app/services/new': typeof AppServicesNewRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/tutorials/new': typeof AppTutorialsNewRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/audit-logs/': typeof AppAuditLogsIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/monitoring/': typeof AppMonitoringIndexRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/posts/': typeof AppPostsIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/tutorials/': typeof AppTutorialsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/_app/orgs/$orgId_/edit': typeof AppOrgsOrgIdEditRoute
  '/_app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/_app/services/$serviceId_/edit': typeof AppServicesServiceIdEditRoute
  '/_app/services/$serviceId_/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/_app/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/associations'
    | '/sign-in/$'
    | '/config/modules'
    | '/config/positions'
    | '/config/representations'
    | '/config/services'
    | '/events/new'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$requestId'
    | '/services/new'
    | '/support/$ticketId'
    | '/tutorials/new'
    | '/users/$userId'
    | '/api/auth/$'
    | '/audit-logs/'
    | '/events/'
    | '/monitoring/'
    | '/orgs/'
    | '/posts/'
    | '/profiles/'
    | '/requests/'
    | '/services/'
    | '/settings/'
    | '/support/'
    | '/tutorials/'
    | '/users/'
    | '/events/$eventId/edit'
    | '/orgs/$orgId/edit'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/form-builder'
    | '/tutorials/$tutorialId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/associations'
    | '/sign-in/$'
    | '/'
    | '/config/modules'
    | '/config/positions'
    | '/config/representations'
    | '/config/services'
    | '/events/new'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$requestId'
    | '/services/new'
    | '/support/$ticketId'
    | '/tutorials/new'
    | '/users/$userId'
    | '/api/auth/$'
    | '/audit-logs'
    | '/events'
    | '/monitoring'
    | '/orgs'
    | '/posts'
    | '/profiles'
    | '/requests'
    | '/services'
    | '/settings'
    | '/support'
    | '/tutorials'
    | '/users'
    | '/events/$eventId/edit'
    | '/orgs/$orgId/edit'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/form-builder'
    | '/tutorials/$tutorialId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/associations'
    | '/sign-in/$'
    | '/_app/'
    | '/_app/config/modules'
    | '/_app/config/positions'
    | '/_app/config/representations'
    | '/_app/config/services'
    | '/_app/events/new'
    | '/_app/orgs/$orgId'
    | '/_app/orgs/new'
    | '/_app/posts/new'
    | '/_app/profiles/$profileId'
    | '/_app/requests/$requestId'
    | '/_app/services/new'
    | '/_app/support/$ticketId'
    | '/_app/tutorials/new'
    | '/_app/users/$userId'
    | '/api/auth/$'
    | '/_app/audit-logs/'
    | '/_app/events/'
    | '/_app/monitoring/'
    | '/_app/orgs/'
    | '/_app/posts/'
    | '/_app/profiles/'
    | '/_app/requests/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/support/'
    | '/_app/tutorials/'
    | '/_app/users/'
    | '/_app/events/$eventId/edit'
    | '/_app/orgs/$orgId_/edit'
    | '/_app/posts/$postId/edit'
    | '/_app/services/$serviceId_/edit'
    | '/_app/services/$serviceId_/form-builder'
    | '/_app/tutorials/$tutorialId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/associations': {
      id: '/_app/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AppAssociationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/': {
      id: '/_app/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof AppTutorialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring/': {
      id: '/_app/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AppMonitoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs/': {
      id: '/_app/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AppAuditLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/new': {
      id: '/_app/tutorials/new'
      path: '/tutorials/new'
      fullPath: '/tutorials/new'
      preLoaderRoute: typeof AppTutorialsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/new': {
      id: '/_app/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AppServicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/$requestId': {
      id: '/_app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$profileId': {
      id: '/_app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof AppProfilesProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/new': {
      id: '/_app/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/new': {
      id: '/_app/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AppOrgsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId': {
      id: '/_app/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/services': {
      id: '/_app/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof AppConfigServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/representations': {
      id: '/_app/config/representations'
      path: '/config/representations'
      fullPath: '/config/representations'
      preLoaderRoute: typeof AppConfigRepresentationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/positions': {
      id: '/_app/config/positions'
      path: '/config/positions'
      fullPath: '/config/positions'
      preLoaderRoute: typeof AppConfigPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/modules': {
      id: '/_app/config/modules'
      path: '/config/modules'
      fullPath: '/config/modules'
      preLoaderRoute: typeof AppConfigModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/$tutorialId/edit': {
      id: '/_app/tutorials/$tutorialId/edit'
      path: '/tutorials/$tutorialId/edit'
      fullPath: '/tutorials/$tutorialId/edit'
      preLoaderRoute: typeof AppTutorialsTutorialIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceId_/form-builder': {
      id: '/_app/services/$serviceId_/form-builder'
      path: '/services/$serviceId/form-builder'
      fullPath: '/services/$serviceId/form-builder'
      preLoaderRoute: typeof AppServicesServiceIdFormBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceId_/edit': {
      id: '/_app/services/$serviceId_/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AppServicesServiceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/$postId/edit': {
      id: '/_app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId_/edit': {
      id: '/_app/orgs/$orgId_/edit'
      path: '/orgs/$orgId/edit'
      fullPath: '/orgs/$orgId/edit'
      preLoaderRoute: typeof AppOrgsOrgIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/edit': {
      id: '/_app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssociationsRoute: typeof AppAssociationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfigModulesRoute: typeof AppConfigModulesRoute
  AppConfigPositionsRoute: typeof AppConfigPositionsRoute
  AppConfigRepresentationsRoute: typeof AppConfigRepresentationsRoute
  AppConfigServicesRoute: typeof AppConfigServicesRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppOrgsOrgIdRoute: typeof AppOrgsOrgIdRoute
  AppOrgsNewRoute: typeof AppOrgsNewRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppProfilesProfileIdRoute: typeof AppProfilesProfileIdRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
  AppServicesNewRoute: typeof AppServicesNewRoute
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
  AppTutorialsNewRoute: typeof AppTutorialsNewRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppAuditLogsIndexRoute: typeof AppAuditLogsIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMonitoringIndexRoute: typeof AppMonitoringIndexRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppTutorialsIndexRoute: typeof AppTutorialsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
  AppOrgsOrgIdEditRoute: typeof AppOrgsOrgIdEditRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
  AppServicesServiceIdEditRoute: typeof AppServicesServiceIdEditRoute
  AppServicesServiceIdFormBuilderRoute: typeof AppServicesServiceIdFormBuilderRoute
  AppTutorialsTutorialIdEditRoute: typeof AppTutorialsTutorialIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssociationsRoute: AppAssociationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfigModulesRoute: AppConfigModulesRoute,
  AppConfigPositionsRoute: AppConfigPositionsRoute,
  AppConfigRepresentationsRoute: AppConfigRepresentationsRoute,
  AppConfigServicesRoute: AppConfigServicesRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppOrgsOrgIdRoute: AppOrgsOrgIdRoute,
  AppOrgsNewRoute: AppOrgsNewRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppProfilesProfileIdRoute: AppProfilesProfileIdRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
  AppServicesNewRoute: AppServicesNewRoute,
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
  AppTutorialsNewRoute: AppTutorialsNewRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppAuditLogsIndexRoute: AppAuditLogsIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMonitoringIndexRoute: AppMonitoringIndexRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppTutorialsIndexRoute: AppTutorialsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
  AppOrgsOrgIdEditRoute: AppOrgsOrgIdEditRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
  AppServicesServiceIdEditRoute: AppServicesServiceIdEditRoute,
  AppServicesServiceIdFormBuilderRoute: AppServicesServiceIdFormBuilderRoute,
  AppTutorialsTutorialIdEditRoute: AppTutorialsTutorialIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
