import { v } from "convex/values";

export enum CountryCode {
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GF = 'GF',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GP = 'GP',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  YE = 'YE',
  YT = 'YT',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
}

export const countryCodeValidator = v.union(
  v.literal(CountryCode.AD),
  v.literal(CountryCode.AE),
  v.literal(CountryCode.AF),
  v.literal(CountryCode.AG),
  v.literal(CountryCode.AI),
  v.literal(CountryCode.AL),
  v.literal(CountryCode.AM),
  v.literal(CountryCode.AO),
  v.literal(CountryCode.AQ),
  v.literal(CountryCode.AR),
  v.literal(CountryCode.AS),
  v.literal(CountryCode.AT),
  v.literal(CountryCode.AU),
  v.literal(CountryCode.AW),
  v.literal(CountryCode.AX),
  v.literal(CountryCode.AZ),
  v.literal(CountryCode.BA),
  v.literal(CountryCode.BB),
  v.literal(CountryCode.BD),
  v.literal(CountryCode.BE),
  v.literal(CountryCode.BF),
  v.literal(CountryCode.BG),
  v.literal(CountryCode.BH),
  v.literal(CountryCode.BI),
  v.literal(CountryCode.BJ),
  v.literal(CountryCode.BL),
  v.literal(CountryCode.BM),
  v.literal(CountryCode.BN),
  v.literal(CountryCode.BO),
  v.literal(CountryCode.BR),
  v.literal(CountryCode.BS),
  v.literal(CountryCode.BT),
  v.literal(CountryCode.BW),
  v.literal(CountryCode.BY),
  v.literal(CountryCode.BZ),
  v.literal(CountryCode.CA),
  v.literal(CountryCode.CC),
  v.literal(CountryCode.CD),
  v.literal(CountryCode.CF),
  v.literal(CountryCode.CG),
  v.literal(CountryCode.CH),
  v.literal(CountryCode.CI),
  v.literal(CountryCode.CK),
  v.literal(CountryCode.CL),
  v.literal(CountryCode.CM),
  v.literal(CountryCode.CN),
  v.literal(CountryCode.CO),
  v.literal(CountryCode.CR),
  v.literal(CountryCode.CU),
  v.literal(CountryCode.CV),
  v.literal(CountryCode.CX),
  v.literal(CountryCode.CY),
  v.literal(CountryCode.CZ),
  v.literal(CountryCode.DE),
  v.literal(CountryCode.DJ),
  v.literal(CountryCode.DK),
  v.literal(CountryCode.DM),
  v.literal(CountryCode.DO),
  v.literal(CountryCode.DZ),
  v.literal(CountryCode.EC),
  v.literal(CountryCode.EE),
  v.literal(CountryCode.EG),
  v.literal(CountryCode.ER),
  v.literal(CountryCode.ES),
  v.literal(CountryCode.ET),
  v.literal(CountryCode.FI),
  v.literal(CountryCode.FJ),
  v.literal(CountryCode.FK),
  v.literal(CountryCode.FM),
  v.literal(CountryCode.FO),
  v.literal(CountryCode.FR),
  v.literal(CountryCode.GA),
  v.literal(CountryCode.GB),
  v.literal(CountryCode.GD),
  v.literal(CountryCode.GE),
  v.literal(CountryCode.GF),
  v.literal(CountryCode.GG),
  v.literal(CountryCode.GH),
  v.literal(CountryCode.GI),
  v.literal(CountryCode.GL),
  v.literal(CountryCode.GM),
  v.literal(CountryCode.GN),
  v.literal(CountryCode.GP),
  v.literal(CountryCode.GQ),
  v.literal(CountryCode.GR),
  v.literal(CountryCode.GS),
  v.literal(CountryCode.GT),
  v.literal(CountryCode.GU),
  v.literal(CountryCode.GW),
  v.literal(CountryCode.GY),
  v.literal(CountryCode.HK),
  v.literal(CountryCode.HN),
  v.literal(CountryCode.HR),
  v.literal(CountryCode.HT),
  v.literal(CountryCode.HU),
  v.literal(CountryCode.ID),
  v.literal(CountryCode.IE),
  v.literal(CountryCode.IL),
  v.literal(CountryCode.IM),
  v.literal(CountryCode.IN),
  v.literal(CountryCode.IO),
  v.literal(CountryCode.IQ),
  v.literal(CountryCode.IR),
  v.literal(CountryCode.IS),
  v.literal(CountryCode.IT),
  v.literal(CountryCode.JE),
  v.literal(CountryCode.JM),
  v.literal(CountryCode.JO),
  v.literal(CountryCode.JP),
  v.literal(CountryCode.KE),
  v.literal(CountryCode.KG),
  v.literal(CountryCode.KH),
  v.literal(CountryCode.KI),
  v.literal(CountryCode.KM),
  v.literal(CountryCode.KN),
  v.literal(CountryCode.KP),
  v.literal(CountryCode.KR),
  v.literal(CountryCode.KW),
  v.literal(CountryCode.KY),
  v.literal(CountryCode.KZ),
  v.literal(CountryCode.LA),
  v.literal(CountryCode.LB),
  v.literal(CountryCode.LC),
  v.literal(CountryCode.LI),
  v.literal(CountryCode.LK),
  v.literal(CountryCode.LR),
  v.literal(CountryCode.LS),
  v.literal(CountryCode.LT),
  v.literal(CountryCode.LU),
  v.literal(CountryCode.LV),
  v.literal(CountryCode.LY),
  v.literal(CountryCode.MA),
  v.literal(CountryCode.MC),
  v.literal(CountryCode.MD),
  v.literal(CountryCode.ME),
  v.literal(CountryCode.MF),
  v.literal(CountryCode.MG),
  v.literal(CountryCode.MH),
  v.literal(CountryCode.MK),
  v.literal(CountryCode.ML),
  v.literal(CountryCode.MM),
  v.literal(CountryCode.MN),
  v.literal(CountryCode.MO),
  v.literal(CountryCode.MP),
  v.literal(CountryCode.MQ),
  v.literal(CountryCode.MR),
  v.literal(CountryCode.MS),
  v.literal(CountryCode.MT),
  v.literal(CountryCode.MU),
  v.literal(CountryCode.MV),
  v.literal(CountryCode.MW),
  v.literal(CountryCode.MX),
  v.literal(CountryCode.MY),
  v.literal(CountryCode.MZ),
  v.literal(CountryCode.NA),
  v.literal(CountryCode.NC),
  v.literal(CountryCode.NE),
  v.literal(CountryCode.NF),
  v.literal(CountryCode.NG),
  v.literal(CountryCode.NI),
  v.literal(CountryCode.NL),
  v.literal(CountryCode.NO),
  v.literal(CountryCode.NP),
  v.literal(CountryCode.NR),
  v.literal(CountryCode.NU),
  v.literal(CountryCode.NZ),
  v.literal(CountryCode.OM),
  v.literal(CountryCode.PA),
  v.literal(CountryCode.PE),
  v.literal(CountryCode.PF),
  v.literal(CountryCode.PG),
  v.literal(CountryCode.PH),
  v.literal(CountryCode.PK),
  v.literal(CountryCode.PL),
  v.literal(CountryCode.PM),
  v.literal(CountryCode.PN),
  v.literal(CountryCode.PR),
  v.literal(CountryCode.PS),
  v.literal(CountryCode.PT),
  v.literal(CountryCode.PW),
  v.literal(CountryCode.PY),
  v.literal(CountryCode.QA),
  v.literal(CountryCode.RE),
  v.literal(CountryCode.RO),
  v.literal(CountryCode.RS),
  v.literal(CountryCode.RU),
  v.literal(CountryCode.RW),
  v.literal(CountryCode.SA),
  v.literal(CountryCode.SB),
  v.literal(CountryCode.SC),
  v.literal(CountryCode.SD),
  v.literal(CountryCode.SE),
  v.literal(CountryCode.SG),
  v.literal(CountryCode.SH),
  v.literal(CountryCode.SI),
  v.literal(CountryCode.SJ),
  v.literal(CountryCode.SK),
  v.literal(CountryCode.SL),
  v.literal(CountryCode.SM),
  v.literal(CountryCode.SN),
  v.literal(CountryCode.SO),
  v.literal(CountryCode.SR),
  v.literal(CountryCode.SS),
  v.literal(CountryCode.ST),
  v.literal(CountryCode.SV),
  v.literal(CountryCode.SY),
  v.literal(CountryCode.SZ),
  v.literal(CountryCode.TC),
  v.literal(CountryCode.TD),
  v.literal(CountryCode.TG),
  v.literal(CountryCode.TH),
  v.literal(CountryCode.TJ),
  v.literal(CountryCode.TK),
  v.literal(CountryCode.TL),
  v.literal(CountryCode.TM),
  v.literal(CountryCode.TN),
  v.literal(CountryCode.TO),
  v.literal(CountryCode.TR),
  v.literal(CountryCode.TT),
  v.literal(CountryCode.TV),
  v.literal(CountryCode.TW),
  v.literal(CountryCode.TZ),
  v.literal(CountryCode.UA),
  v.literal(CountryCode.UG),
  v.literal(CountryCode.US),
  v.literal(CountryCode.UY),
  v.literal(CountryCode.UZ),
  v.literal(CountryCode.VA),
  v.literal(CountryCode.VC),
  v.literal(CountryCode.VE),
  v.literal(CountryCode.VG),
  v.literal(CountryCode.VI),
  v.literal(CountryCode.VN),
  v.literal(CountryCode.VU),
  v.literal(CountryCode.WF),
  v.literal(CountryCode.WS),
  v.literal(CountryCode.YE),
  v.literal(CountryCode.YT),
  v.literal(CountryCode.ZA),
  v.literal(CountryCode.ZM),
  v.literal(CountryCode.ZW)
);