import { ConvexError } from "convex/values";

/**
 * Error codes for the application
 */
export const ErrorCode = {
  // Auth
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // Orgs
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_SLUG_EXISTS: "ORG_SLUG_EXISTS",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  CANNOT_REMOVE_SELF: "CANNOT_REMOVE_SELF",

  // Services
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  SERVICE_SLUG_EXISTS: "SERVICE_SLUG_EXISTS",
  SERVICE_ALREADY_ACTIVATED: "SERVICE_ALREADY_ACTIVATED",
  SERVICE_NOT_AVAILABLE: "SERVICE_NOT_AVAILABLE",

  // Requests
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  REQUEST_NOT_DRAFT: "REQUEST_NOT_DRAFT",
  REQUEST_CANNOT_CANCEL: "REQUEST_CANNOT_CANCEL",

  // Appointments
  SLOT_NOT_AVAILABLE: "SLOT_NOT_AVAILABLE",
  SLOT_FULLY_BOOKED: "SLOT_FULLY_BOOKED",
  SLOT_HAS_BOOKINGS: "SLOT_HAS_BOOKINGS",
  APPOINTMENT_ALREADY_EXISTS: "APPOINTMENT_ALREADY_EXISTS",
  APPOINTMENT_ALREADY_CANCELLED: "APPOINTMENT_ALREADY_CANCELLED",

  // Documents
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",

  // Profiles
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",

  // Posts
  POST_NOT_FOUND: "POST_NOT_FOUND",
  POST_SLUG_EXISTS: "POST_SLUG_EXISTS",
  POST_DOCUMENT_REQUIRED: "POST_DOCUMENT_REQUIRED",

  // Tutorials
  TUTORIAL_NOT_FOUND: "TUTORIAL_NOT_FOUND",
  TUTORIAL_SLUG_EXISTS: "TUTORIAL_SLUG_EXISTS",

  // Community Events
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_SLUG_EXISTS: "EVENT_SLUG_EXISTS",

  // Generic
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Role Config
  POSITION_NOT_FOUND: "POSITION_NOT_FOUND",
  POSITION_CODE_EXISTS: "POSITION_CODE_EXISTS",
  POSITION_REQUIRED: "POSITION_REQUIRED",
  ROLE_MODULE_NOT_FOUND: "ROLE_MODULE_NOT_FOUND",
  ROLE_MODULE_CODE_EXISTS: "ROLE_MODULE_CODE_EXISTS",
  ROLE_MODULE_SYSTEM: "ROLE_MODULE_SYSTEM",
  ROLE_CONFIG_ALREADY_INITIALIZED: "ROLE_CONFIG_ALREADY_INITIALIZED",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  MINISTRY_GROUP_EXISTS: "MINISTRY_GROUP_EXISTS",

  // Module Configurator
  MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
  MODULE_KEY_EXISTS: "MODULE_KEY_EXISTS",
  MODULE_CORE_IMMUTABLE: "MODULE_CORE_IMMUTABLE",
  MODULE_DEPENDENCY_MISSING: "MODULE_DEPENDENCY_MISSING",
  MODULE_NOT_CONFIGURED: "MODULE_NOT_CONFIGURED",

  // Security
  POLICY_NOT_FOUND: "POLICY_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Create a standardized ConvexError
 */
export function error(code: ErrorCode, message?: string): ConvexError<string> {
  return new ConvexError(message ?? code);
}

/**
 * Throw if condition is false
 */
export function ensure(
  condition: unknown,
  code: ErrorCode,
  message?: string,
): asserts condition {
  if (!condition) {
    throw error(code, message);
  }
}
