// ---------------------------------------------------------------------------
// Predefined card templates – ported from PredefinedTemplates.swift
// ---------------------------------------------------------------------------

import type { CardElement, CardTemplate } from "./card-element";

export interface TemplateInfo {
  id: string;
  name: string;
  description: string;
  category: string;
  template: CardTemplate;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let _tid = 0;
function tid(): string {
  _tid += 1;
  return `tpl-${_tid}`;
}

function el(partial: Partial<CardElement> & { id: string; type: CardElement["type"] }): CardElement {
  return {
    id: partial.id,
    type: partial.type,
    x: partial.x ?? 0,
    y: partial.y ?? 0,
    width: partial.width ?? 200,
    height: partial.height ?? 40,
    rotation: partial.rotation ?? 0,
    isLocked: partial.isLocked ?? false,
    isVisible: partial.isVisible ?? true,
    zIndex: partial.zIndex ?? 0,
    textContent: partial.textContent ?? "",
    fontName: partial.fontName ?? "Helvetica",
    fontSize: partial.fontSize ?? 16,
    textColor: partial.textColor ?? "#000000",
    textAlignment: partial.textAlignment ?? "left",
    isBold: partial.isBold ?? false,
    isItalic: partial.isItalic ?? false,
    isDynamicField: partial.isDynamicField ?? false,
    fieldKey: partial.fieldKey ?? "",
    imageData: partial.imageData ?? null,
    fillColor: partial.fillColor ?? "#FFFFFF",
    strokeColor: partial.strokeColor ?? "#000000",
    strokeWidth: partial.strokeWidth ?? 1,
    cornerRadius: partial.cornerRadius ?? 0,
    codeContent: partial.codeContent ?? "",
  };
}

function now(): string {
  return new Date().toISOString();
}

// ---------------------------------------------------------------------------
// 1. Badge Employé
// ---------------------------------------------------------------------------

function createBadgeEmploye(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-badge-employe",
    name: "Badge Employé",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#1A365D",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: true,
    magneticTracks: ["", "", ""],
    frontElements: [
      // Company name header
      el({
        id: tid(),
        type: "text",
        x: 308,
        y: 30,
        width: 400,
        height: 50,
        textContent: "ENTREPRISE",
        fontName: "Helvetica-Bold",
        fontSize: 28,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Header line
      el({
        id: tid(),
        type: "line",
        x: 50,
        y: 85,
        width: 916,
        height: 3,
        strokeColor: "#E2B93B",
        strokeWidth: 3,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Photo placeholder
      el({
        id: tid(),
        type: "rectangle",
        x: 60,
        y: 120,
        width: 220,
        height: 280,
        fillColor: "#2D4A7A",
        strokeColor: "#E2B93B",
        strokeWidth: 2,
        cornerRadius: 8,
        zIndex: 1,
      }),
      // Photo image
      el({
        id: tid(),
        type: "image",
        x: 70,
        y: 130,
        width: 200,
        height: 260,
        isDynamicField: true,
        fieldKey: "photo",
        zIndex: 2,
      }),
      // Full name
      el({
        id: tid(),
        type: "text",
        x: 320,
        y: 130,
        width: 640,
        height: 45,
        textContent: "NOM Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 26,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "fullName",
        zIndex: 2,
      }),
      // Position / title
      el({
        id: tid(),
        type: "text",
        x: 320,
        y: 185,
        width: 640,
        height: 35,
        textContent: "Poste / Fonction",
        fontName: "Helvetica",
        fontSize: 20,
        textColor: "#E2B93B",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "position",
        zIndex: 2,
      }),
      // Department
      el({
        id: tid(),
        type: "text",
        x: 320,
        y: 230,
        width: 640,
        height: 30,
        textContent: "Département",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#CCCCCC",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "department",
        zIndex: 2,
      }),
      // Employee ID
      el({
        id: tid(),
        type: "text",
        x: 320,
        y: 275,
        width: 640,
        height: 30,
        textContent: "ID: EMP-00000",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#CCCCCC",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "employeeId",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 830,
        y: 350,
        width: 120,
        height: 120,
        codeContent: "EMP-00000",
        isDynamicField: true,
        fieldKey: "employeeId",
        zIndex: 2,
      }),
      // Barcode
      el({
        id: tid(),
        type: "barcode",
        x: 60,
        y: 500,
        width: 350,
        height: 60,
        codeContent: "EMP00000",
        isDynamicField: true,
        fieldKey: "barcode",
        zIndex: 2,
      }),
      // Validity
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 580,
        width: 400,
        height: 25,
        textContent: "Valide jusqu'au: 31/12/2026",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "validUntil",
        zIndex: 2,
      }),
    ],
    backElements: [
      // Back header
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 40,
        width: 500,
        height: 40,
        textContent: "INFORMATIONS IMPORTANTES",
        fontName: "Helvetica-Bold",
        fontSize: 20,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Instructions
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 120,
        width: 896,
        height: 200,
        textContent:
          "Ce badge est strictement personnel et incessible.\nEn cas de perte, veuillez contacter immédiatement\nle service des ressources humaines.\n\nLe port du badge est obligatoire dans l'enceinte\nde l'entreprise.",
        fontName: "Helvetica",
        fontSize: 15,
        textColor: "#CCCCCC",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Contact
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 400,
        width: 500,
        height: 30,
        textContent: "RH: +241 01 00 00 00",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Magnetic stripe placeholder
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 520,
        width: 1016,
        height: 80,
        fillColor: "#333333",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 1,
      }),
    ],
  };
}

// ---------------------------------------------------------------------------
// 2. Carte Membre
// ---------------------------------------------------------------------------

function createCarteMembre(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-carte-membre",
    name: "Carte Membre",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#0D7C3E",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: true,
    magneticTracks: ["", "", ""],
    frontElements: [
      // Club / organisation name
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 25,
        width: 500,
        height: 50,
        textContent: "CLUB / ASSOCIATION",
        fontName: "Helvetica-Bold",
        fontSize: 26,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Subtitle
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 75,
        width: 500,
        height: 30,
        textContent: "Carte de Membre",
        fontName: "Helvetica",
        fontSize: 18,
        textColor: "#A8E6CF",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Separator line
      el({
        id: tid(),
        type: "line",
        x: 100,
        y: 115,
        width: 816,
        height: 2,
        strokeColor: "#FFFFFF",
        strokeWidth: 2,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Photo
      el({
        id: tid(),
        type: "image",
        x: 60,
        y: 145,
        width: 180,
        height: 220,
        isDynamicField: true,
        fieldKey: "photo",
        zIndex: 2,
      }),
      // Photo frame
      el({
        id: tid(),
        type: "rectangle",
        x: 55,
        y: 140,
        width: 190,
        height: 230,
        fillColor: "transparent",
        strokeColor: "#FFFFFF",
        strokeWidth: 2,
        cornerRadius: 6,
        zIndex: 1,
      }),
      // Name
      el({
        id: tid(),
        type: "text",
        x: 280,
        y: 150,
        width: 680,
        height: 40,
        textContent: "NOM Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 24,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "fullName",
        zIndex: 2,
      }),
      // Member number
      el({
        id: tid(),
        type: "text",
        x: 280,
        y: 200,
        width: 680,
        height: 30,
        textContent: "N° Membre: 00000",
        fontName: "Helvetica",
        fontSize: 18,
        textColor: "#A8E6CF",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "memberNumber",
        zIndex: 2,
      }),
      // Membership type
      el({
        id: tid(),
        type: "text",
        x: 280,
        y: 245,
        width: 680,
        height: 30,
        textContent: "Type: Standard",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#DDDDDD",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "membershipType",
        zIndex: 2,
      }),
      // Since
      el({
        id: tid(),
        type: "text",
        x: 280,
        y: 285,
        width: 680,
        height: 30,
        textContent: "Membre depuis: 01/01/2024",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#BBBBBB",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "memberSince",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 830,
        y: 400,
        width: 120,
        height: 120,
        codeContent: "MEMBER-00000",
        isDynamicField: true,
        fieldKey: "memberNumber",
        zIndex: 2,
      }),
      // Validity
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 580,
        width: 500,
        height: 25,
        textContent: "Valide jusqu'au: 31/12/2026",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "validUntil",
        zIndex: 2,
      }),
    ],
    backElements: [
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 40,
        width: 500,
        height: 40,
        textContent: "CONDITIONS D'UTILISATION",
        fontName: "Helvetica-Bold",
        fontSize: 20,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 120,
        width: 896,
        height: 200,
        textContent:
          "Cette carte est personnelle et incessible.\nElle doit être présentée à chaque visite.\nEn cas de perte, contactez le secrétariat.\n\nL'adhérent s'engage à respecter le règlement\nintérieur de l'association.",
        fontName: "Helvetica",
        fontSize: 15,
        textColor: "#CCCCCC",
        textAlignment: "center",
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 400,
        width: 500,
        height: 30,
        textContent: "Contact: info@association.org",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "center",
        zIndex: 2,
      }),
    ],
  };
}

// ---------------------------------------------------------------------------
// 3. Carte Étudiant
// ---------------------------------------------------------------------------

function createCarteEtudiant(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-carte-etudiant",
    name: "Carte Étudiant",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#1B3A5C",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: true,
    magneticTracks: ["", "", ""],
    frontElements: [
      // University name
      el({
        id: tid(),
        type: "text",
        x: 200,
        y: 20,
        width: 616,
        height: 45,
        textContent: "UNIVERSITÉ",
        fontName: "Helvetica-Bold",
        fontSize: 28,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Subtitle
      el({
        id: tid(),
        type: "text",
        x: 200,
        y: 65,
        width: 616,
        height: 30,
        textContent: "CARTE D'ÉTUDIANT",
        fontName: "Helvetica-Bold",
        fontSize: 18,
        textColor: "#FFD700",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Academic year
      el({
        id: tid(),
        type: "text",
        x: 200,
        y: 95,
        width: 616,
        height: 25,
        textContent: "Année Académique 2025-2026",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#CCCCCC",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "academicYear",
        zIndex: 2,
      }),
      // Top line
      el({
        id: tid(),
        type: "line",
        x: 50,
        y: 125,
        width: 916,
        height: 2,
        strokeColor: "#FFD700",
        strokeWidth: 2,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Photo frame
      el({
        id: tid(),
        type: "rectangle",
        x: 55,
        y: 150,
        width: 200,
        height: 250,
        fillColor: "#2A4F76",
        strokeColor: "#FFD700",
        strokeWidth: 2,
        cornerRadius: 4,
        zIndex: 1,
      }),
      // Photo
      el({
        id: tid(),
        type: "image",
        x: 65,
        y: 160,
        width: 180,
        height: 230,
        isDynamicField: true,
        fieldKey: "photo",
        zIndex: 2,
      }),
      // Student name
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 155,
        width: 670,
        height: 40,
        textContent: "NOM Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 24,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "fullName",
        zIndex: 2,
      }),
      // Student number
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 205,
        width: 670,
        height: 30,
        textContent: "N° Étudiant: 20250000",
        fontName: "Helvetica",
        fontSize: 18,
        textColor: "#FFD700",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "studentNumber",
        zIndex: 2,
      }),
      // Faculty
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 250,
        width: 670,
        height: 30,
        textContent: "Faculté des Sciences",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#DDDDDD",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "faculty",
        zIndex: 2,
      }),
      // Level
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 290,
        width: 670,
        height: 30,
        textContent: "Niveau: Licence 3",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#CCCCCC",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "level",
        zIndex: 2,
      }),
      // Date of birth
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 330,
        width: 670,
        height: 25,
        textContent: "Né(e) le: 01/01/2000",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "dateOfBirth",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 830,
        y: 380,
        width: 120,
        height: 120,
        codeContent: "STU-20250000",
        isDynamicField: true,
        fieldKey: "studentNumber",
        zIndex: 2,
      }),
      // Barcode
      el({
        id: tid(),
        type: "barcode",
        x: 60,
        y: 500,
        width: 350,
        height: 55,
        codeContent: "20250000",
        isDynamicField: true,
        fieldKey: "barcode",
        zIndex: 2,
      }),
      // Validity
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 575,
        width: 500,
        height: 25,
        textContent: "Valide jusqu'au: 30/09/2026",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "validUntil",
        zIndex: 2,
      }),
    ],
    backElements: [
      el({
        id: tid(),
        type: "text",
        x: 208,
        y: 40,
        width: 600,
        height: 40,
        textContent: "RÈGLEMENT",
        fontName: "Helvetica-Bold",
        fontSize: 22,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 110,
        width: 896,
        height: 250,
        textContent:
          "Cette carte est strictement personnelle.\nElle doit être présentée lors de tout examen\net pour accéder aux locaux de l'université.\n\nEn cas de perte ou de vol, le titulaire doit\nimmédiatement en informer le service\nde la scolarité.",
        fontName: "Helvetica",
        fontSize: 15,
        textColor: "#CCCCCC",
        textAlignment: "center",
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 208,
        y: 420,
        width: 600,
        height: 30,
        textContent: "Scolarité: +241 01 00 00 00",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Magnetic stripe
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 520,
        width: 1016,
        height: 80,
        fillColor: "#333333",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 1,
      }),
    ],
  };
}

// ---------------------------------------------------------------------------
// 4. Carte Visiteur
// ---------------------------------------------------------------------------

function createCarteVisiteur(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-carte-visiteur",
    name: "Carte Visiteur",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#F5F5F5",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: false,
    magneticTracks: ["", "", ""],
    frontElements: [
      // VISITEUR header band
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 0,
        width: 1016,
        height: 100,
        fillColor: "#D32F2F",
        strokeColor: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
        zIndex: 1,
      }),
      el({
        id: tid(),
        type: "text",
        x: 258,
        y: 25,
        width: 500,
        height: 55,
        textContent: "VISITEUR",
        fontName: "Helvetica-Bold",
        fontSize: 36,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Visitor name
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 130,
        width: 896,
        height: 45,
        textContent: "NOM Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 28,
        textColor: "#333333",
        textAlignment: "center",
        isBold: true,
        isDynamicField: true,
        fieldKey: "fullName",
        zIndex: 2,
      }),
      // Company
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 185,
        width: 896,
        height: 35,
        textContent: "Société",
        fontName: "Helvetica",
        fontSize: 20,
        textColor: "#666666",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "company",
        zIndex: 2,
      }),
      // Separator
      el({
        id: tid(),
        type: "line",
        x: 200,
        y: 240,
        width: 616,
        height: 2,
        strokeColor: "#D32F2F",
        strokeWidth: 2,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Visiting label
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 265,
        width: 896,
        height: 30,
        textContent: "Visite à:",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#999999",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Host name
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 300,
        width: 896,
        height: 35,
        textContent: "Nom de l'hôte",
        fontName: "Helvetica-Bold",
        fontSize: 22,
        textColor: "#333333",
        textAlignment: "center",
        isBold: true,
        isDynamicField: true,
        fieldKey: "hostName",
        zIndex: 2,
      }),
      // Date / time
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 365,
        width: 896,
        height: 30,
        textContent: "Date: 01/01/2026  Heure: 09:00",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#666666",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "visitDateTime",
        zIndex: 2,
      }),
      // Badge number
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 420,
        width: 896,
        height: 30,
        textContent: "Badge N°: V-0000",
        fontName: "Helvetica",
        fontSize: 18,
        textColor: "#D32F2F",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "badgeNumber",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 430,
        y: 470,
        width: 140,
        height: 140,
        codeContent: "V-0000",
        isDynamicField: true,
        fieldKey: "badgeNumber",
        zIndex: 2,
      }),
    ],
    backElements: [],
  };
}

// ---------------------------------------------------------------------------
// 5. Badge Événement
// ---------------------------------------------------------------------------

function createBadgeEvenement(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-badge-evenement",
    name: "Badge Événement",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#4A148C",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: true,
    magneticTracks: ["", "", ""],
    frontElements: [
      // Event name
      el({
        id: tid(),
        type: "text",
        x: 108,
        y: 30,
        width: 800,
        height: 50,
        textContent: "NOM DE L'ÉVÉNEMENT",
        fontName: "Helvetica-Bold",
        fontSize: 28,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Date / location
      el({
        id: tid(),
        type: "text",
        x: 108,
        y: 80,
        width: 800,
        height: 30,
        textContent: "01-03 Janvier 2026 | Libreville",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#CE93D8",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "eventDateLocation",
        zIndex: 2,
      }),
      // Accent line
      el({
        id: tid(),
        type: "line",
        x: 100,
        y: 120,
        width: 816,
        height: 3,
        strokeColor: "#FF6F00",
        strokeWidth: 3,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Attendee type badge
      el({
        id: tid(),
        type: "rectangle",
        x: 350,
        y: 145,
        width: 316,
        height: 45,
        fillColor: "#FF6F00",
        strokeColor: "transparent",
        strokeWidth: 0,
        cornerRadius: 22,
        zIndex: 1,
      }),
      el({
        id: tid(),
        type: "text",
        x: 350,
        y: 150,
        width: 316,
        height: 35,
        textContent: "PARTICIPANT",
        fontName: "Helvetica-Bold",
        fontSize: 20,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        isDynamicField: true,
        fieldKey: "attendeeType",
        zIndex: 2,
      }),
      // Photo
      el({
        id: tid(),
        type: "image",
        x: 60,
        y: 220,
        width: 160,
        height: 200,
        isDynamicField: true,
        fieldKey: "photo",
        zIndex: 2,
      }),
      // Photo frame
      el({
        id: tid(),
        type: "rectangle",
        x: 55,
        y: 215,
        width: 170,
        height: 210,
        fillColor: "transparent",
        strokeColor: "#FF6F00",
        strokeWidth: 2,
        cornerRadius: 8,
        zIndex: 1,
      }),
      // Name
      el({
        id: tid(),
        type: "text",
        x: 260,
        y: 230,
        width: 700,
        height: 45,
        textContent: "NOM Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 26,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "fullName",
        zIndex: 2,
      }),
      // Organisation
      el({
        id: tid(),
        type: "text",
        x: 260,
        y: 285,
        width: 700,
        height: 30,
        textContent: "Organisation",
        fontName: "Helvetica",
        fontSize: 18,
        textColor: "#CE93D8",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "organisation",
        zIndex: 2,
      }),
      // Title
      el({
        id: tid(),
        type: "text",
        x: 260,
        y: 325,
        width: 700,
        height: 30,
        textContent: "Titre / Fonction",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#BBBBBB",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "title",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 430,
        y: 460,
        width: 140,
        height: 140,
        codeContent: "EVT-00000",
        isDynamicField: true,
        fieldKey: "registrationId",
        zIndex: 2,
      }),
    ],
    backElements: [
      // Schedule or programme summary
      el({
        id: tid(),
        type: "text",
        x: 208,
        y: 40,
        width: 600,
        height: 40,
        textContent: "PROGRAMME",
        fontName: "Helvetica-Bold",
        fontSize: 22,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 110,
        width: 896,
        height: 300,
        textContent:
          "09:00 - Accueil et enregistrement\n10:00 - Conférence d'ouverture\n12:00 - Pause déjeuner\n14:00 - Ateliers\n16:00 - Table ronde\n17:30 - Clôture",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#CCCCCC",
        textAlignment: "left",
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 108,
        y: 500,
        width: 800,
        height: 25,
        textContent: "Wi-Fi: EVENT2026 | Mot de passe: bienvenue",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#AAAAAA",
        textAlignment: "center",
        zIndex: 2,
      }),
    ],
  };
}

// ---------------------------------------------------------------------------
// 6. Carte Consulaire (Gabonese consular card)
// ---------------------------------------------------------------------------

function createCarteConsulaire(): CardTemplate {
  const ts = now();
  return {
    id: "predefined-carte-consulaire",
    name: "Carte Consulaire",
    createdAt: ts,
    updatedAt: ts,
    backgroundColor: "#003DA5",
    frontBackgroundImage: null,
    backBackgroundImage: null,
    backgroundOpacity: 1,
    printDuplex: true,
    magneticTracks: ["", "", ""],
    frontElements: [
      // Top band with national colours
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 0,
        width: 339,
        height: 8,
        fillColor: "#009E49",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 339,
        y: 0,
        width: 338,
        height: 8,
        fillColor: "#FFD100",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 677,
        y: 0,
        width: 339,
        height: 8,
        fillColor: "#003DA5",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      // Republic header
      el({
        id: tid(),
        type: "text",
        x: 200,
        y: 15,
        width: 616,
        height: 30,
        textContent: "RÉPUBLIQUE GABONAISE",
        fontName: "Helvetica-Bold",
        fontSize: 18,
        textColor: "#FFD100",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Motto
      el({
        id: tid(),
        type: "text",
        x: 200,
        y: 42,
        width: 616,
        height: 22,
        textContent: "Union - Travail - Justice",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isItalic: true,
        zIndex: 2,
      }),
      // Card title
      el({
        id: tid(),
        type: "text",
        x: 158,
        y: 68,
        width: 700,
        height: 40,
        textContent: "CARTE CONSULAIRE",
        fontName: "Helvetica-Bold",
        fontSize: 24,
        textColor: "#FFFFFF",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Consulate name
      el({
        id: tid(),
        type: "text",
        x: 158,
        y: 105,
        width: 700,
        height: 25,
        textContent: "Consulat Général du Gabon",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#CCCCCC",
        textAlignment: "center",
        isDynamicField: true,
        fieldKey: "consulateName",
        zIndex: 2,
      }),
      // Gold separator
      el({
        id: tid(),
        type: "line",
        x: 50,
        y: 138,
        width: 916,
        height: 2,
        strokeColor: "#FFD100",
        strokeWidth: 2,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Photo frame
      el({
        id: tid(),
        type: "rectangle",
        x: 50,
        y: 155,
        width: 210,
        height: 270,
        fillColor: "#1A2E5A",
        strokeColor: "#FFD100",
        strokeWidth: 2,
        cornerRadius: 4,
        zIndex: 1,
      }),
      // Photo
      el({
        id: tid(),
        type: "image",
        x: 60,
        y: 165,
        width: 190,
        height: 250,
        isDynamicField: true,
        fieldKey: "photo",
        zIndex: 2,
      }),
      // Nom label
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 158,
        width: 150,
        height: 22,
        textContent: "Nom:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Nom value
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 178,
        width: 450,
        height: 35,
        textContent: "NOM",
        fontName: "Helvetica-Bold",
        fontSize: 22,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "lastName",
        zIndex: 2,
      }),
      // Prénom label
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 218,
        width: 150,
        height: 22,
        textContent: "Prénom(s):",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Prénom value
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 238,
        width: 450,
        height: 30,
        textContent: "Prénom",
        fontName: "Helvetica-Bold",
        fontSize: 20,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "firstName",
        zIndex: 2,
      }),
      // Date of birth label
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 278,
        width: 200,
        height: 22,
        textContent: "Date de naissance:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Date of birth value
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 298,
        width: 300,
        height: 28,
        textContent: "01/01/1990",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "dateOfBirth",
        zIndex: 2,
      }),
      // Place of birth label
      el({
        id: tid(),
        type: "text",
        x: 580,
        y: 278,
        width: 200,
        height: 22,
        textContent: "Lieu de naissance:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Place of birth value
      el({
        id: tid(),
        type: "text",
        x: 580,
        y: 298,
        width: 380,
        height: 28,
        textContent: "Libreville",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "placeOfBirth",
        zIndex: 2,
      }),
      // Nationality label
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 335,
        width: 200,
        height: 22,
        textContent: "Nationalité:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Nationality value
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 355,
        width: 300,
        height: 28,
        textContent: "Gabonaise",
        fontName: "Helvetica",
        fontSize: 16,
        textColor: "#FFFFFF",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "nationality",
        zIndex: 2,
      }),
      // Card number label
      el({
        id: tid(),
        type: "text",
        x: 580,
        y: 335,
        width: 200,
        height: 22,
        textContent: "N° Carte:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Card number value
      el({
        id: tid(),
        type: "text",
        x: 580,
        y: 355,
        width: 380,
        height: 28,
        textContent: "CC-000000",
        fontName: "Helvetica-Bold",
        fontSize: 16,
        textColor: "#FFD100",
        textAlignment: "left",
        isBold: true,
        isDynamicField: true,
        fieldKey: "cardNumber",
        zIndex: 2,
      }),
      // Address label
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 392,
        width: 200,
        height: 22,
        textContent: "Adresse:",
        fontName: "Helvetica",
        fontSize: 12,
        textColor: "#AAAAAA",
        textAlignment: "left",
        zIndex: 2,
      }),
      // Address value
      el({
        id: tid(),
        type: "text",
        x: 290,
        y: 412,
        width: 670,
        height: 28,
        textContent: "Adresse complète",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#DDDDDD",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "address",
        zIndex: 2,
      }),
      // QR Code
      el({
        id: tid(),
        type: "qrCode",
        x: 830,
        y: 155,
        width: 130,
        height: 130,
        codeContent: "CC-000000",
        isDynamicField: true,
        fieldKey: "cardNumber",
        zIndex: 2,
      }),
      // Bottom gold line
      el({
        id: tid(),
        type: "line",
        x: 50,
        y: 460,
        width: 916,
        height: 2,
        strokeColor: "#FFD100",
        strokeWidth: 2,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Dates of issue / expiry
      el({
        id: tid(),
        type: "text",
        x: 50,
        y: 475,
        width: 450,
        height: 25,
        textContent: "Délivrée le: 01/01/2026",
        fontName: "Helvetica",
        fontSize: 13,
        textColor: "#AAAAAA",
        textAlignment: "left",
        isDynamicField: true,
        fieldKey: "issueDate",
        zIndex: 2,
      }),
      el({
        id: tid(),
        type: "text",
        x: 516,
        y: 475,
        width: 450,
        height: 25,
        textContent: "Expire le: 01/01/2031",
        fontName: "Helvetica",
        fontSize: 13,
        textColor: "#AAAAAA",
        textAlignment: "right",
        isDynamicField: true,
        fieldKey: "expiryDate",
        zIndex: 2,
      }),
      // Barcode
      el({
        id: tid(),
        type: "barcode",
        x: 250,
        y: 520,
        width: 516,
        height: 55,
        codeContent: "CC000000",
        isDynamicField: true,
        fieldKey: "barcode",
        zIndex: 2,
      }),
      // Bottom band (green-yellow-blue)
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 640,
        width: 339,
        height: 8,
        fillColor: "#009E49",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 339,
        y: 640,
        width: 338,
        height: 8,
        fillColor: "#FFD100",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 677,
        y: 640,
        width: 339,
        height: 8,
        fillColor: "#003DA5",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
    ],
    backElements: [
      // Top band
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 0,
        width: 339,
        height: 8,
        fillColor: "#009E49",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 339,
        y: 0,
        width: 338,
        height: 8,
        fillColor: "#FFD100",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 677,
        y: 0,
        width: 339,
        height: 8,
        fillColor: "#003DA5",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      // Title
      el({
        id: tid(),
        type: "text",
        x: 158,
        y: 30,
        width: 700,
        height: 35,
        textContent: "CONSULAT GÉNÉRAL DU GABON",
        fontName: "Helvetica-Bold",
        fontSize: 20,
        textColor: "#FFD100",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Consulate address
      el({
        id: tid(),
        type: "text",
        x: 108,
        y: 75,
        width: 800,
        height: 80,
        textContent:
          "Adresse du Consulat\nTél: +241 01 00 00 00\nEmail: consulat@gabon.gouv.ga",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#CCCCCC",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Separator
      el({
        id: tid(),
        type: "line",
        x: 100,
        y: 170,
        width: 816,
        height: 2,
        strokeColor: "#FFD100",
        strokeWidth: 1,
        fillColor: "transparent",
        zIndex: 1,
      }),
      // Notice text
      el({
        id: tid(),
        type: "text",
        x: 60,
        y: 190,
        width: 896,
        height: 220,
        textContent:
          "Cette carte consulaire est délivrée conformément\naux dispositions de la Convention de Vienne sur\nles relations consulaires du 24 avril 1963.\n\nElle atteste de l'immatriculation du titulaire\nauprès du Consulat Général du Gabon.\n\nEn cas de perte ou de vol, prière de retourner\ncette carte au Consulat le plus proche.",
        fontName: "Helvetica",
        fontSize: 14,
        textColor: "#CCCCCC",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Emergency contact
      el({
        id: tid(),
        type: "text",
        x: 108,
        y: 430,
        width: 800,
        height: 30,
        textContent: "Urgences consulaires: +241 01 00 00 00",
        fontName: "Helvetica-Bold",
        fontSize: 14,
        textColor: "#FFD100",
        textAlignment: "center",
        isBold: true,
        zIndex: 2,
      }),
      // Magnetic stripe
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 490,
        width: 1016,
        height: 80,
        fillColor: "#1A1A1A",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 1,
      }),
      // Signature line
      el({
        id: tid(),
        type: "line",
        x: 350,
        y: 600,
        width: 316,
        height: 1,
        strokeColor: "#AAAAAA",
        strokeWidth: 1,
        fillColor: "transparent",
        zIndex: 1,
      }),
      el({
        id: tid(),
        type: "text",
        x: 350,
        y: 605,
        width: 316,
        height: 20,
        textContent: "Signature du titulaire",
        fontName: "Helvetica",
        fontSize: 11,
        textColor: "#AAAAAA",
        textAlignment: "center",
        zIndex: 2,
      }),
      // Bottom band
      el({
        id: tid(),
        type: "rectangle",
        x: 0,
        y: 640,
        width: 339,
        height: 8,
        fillColor: "#009E49",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 339,
        y: 640,
        width: 338,
        height: 8,
        fillColor: "#FFD100",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
      el({
        id: tid(),
        type: "rectangle",
        x: 677,
        y: 640,
        width: 339,
        height: 8,
        fillColor: "#003DA5",
        strokeColor: "transparent",
        strokeWidth: 0,
        zIndex: 3,
      }),
    ],
  };
}

// ---------------------------------------------------------------------------
// Export all predefined templates
// ---------------------------------------------------------------------------

export const PREDEFINED_TEMPLATES: TemplateInfo[] = [
  {
    id: "predefined-badge-employe",
    name: "Badge Employé",
    description: "Badge d'identification pour les employés avec photo, nom, poste et code-barres.",
    category: "Entreprise",
    template: createBadgeEmploye(),
  },
  {
    id: "predefined-carte-membre",
    name: "Carte Membre",
    description: "Carte de membre pour clubs et associations avec numéro de membre et QR code.",
    category: "Association",
    template: createCarteMembre(),
  },
  {
    id: "predefined-carte-etudiant",
    name: "Carte Étudiant",
    description: "Carte d'étudiant universitaire avec faculté, numéro étudiant et année académique.",
    category: "Éducation",
    template: createCarteEtudiant(),
  },
  {
    id: "predefined-carte-visiteur",
    name: "Carte Visiteur",
    description: "Badge visiteur temporaire avec nom, société, hôte et horodatage de la visite.",
    category: "Entreprise",
    template: createCarteVisiteur(),
  },
  {
    id: "predefined-badge-evenement",
    name: "Badge Événement",
    description: "Badge pour conférences et événements avec type de participant et programme.",
    category: "Événement",
    template: createBadgeEvenement(),
  },
  {
    id: "predefined-carte-consulaire",
    name: "Carte Consulaire",
    description:
      "Carte consulaire officielle de la République Gabonaise avec les couleurs nationales, informations d'identité complètes et bande magnétique.",
    category: "Gouvernement",
    template: createCarteConsulaire(),
  },
];
